#!/usr/bin/env bash
#10
i=1
while [ "$i" -ne 101 ]
do
	if (( "$i" % 3 == 0 && "$i" % 5 == 0 ))
	then
		printf "FizzBuzz\n"
	elif (( "$i" % 3 == 0 ))
	then
		printf "Fizz\n"
	
	elif (( "$i" %  5 == 0 ))
	then
	        printf "Buzz\n"
	else
		echo "$i"
	fi
		(i++)
	done
