#!/usr/bin/env bash
#11 
IFS= ":"
while read -r username passwd userid groupid useridinfo home commandshell
do
	echo "The user $username is part of the $groupid gang, lives in $home  and rides $commandshell. $userid  place is protected by the passcode $passwd, more info about the user here: $useridinfo"
done
