#!/usr/bin/env bash
#read pass
IFS=":"
  while read -r USERNAME passwd userid groupid info home commandshell
  do
	  echo "The user $USERNAME is part of the $groupid gang, lives in $home and rides $commandshell. $userid's place is protected by the passcode $passwd, more info about the user here: $info"
  done < /etc/passwd
