#!/usr/bin/env bash
#11 
IFS=":"
while read -r USERNAME PASSWORD USERID GROUPID  USERID  USERIDINFO HOME_DIRECTORY COMMANDSHELL
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY  and rides $COMMANDSHELL. $USERID place is protected by the passcode $PASSWORD, more info about the user here: $USERIDINFO"
done < etc/passwd
