#!/usr/bin/env bash
#this my script bash

bestschool=2;

while [ "$bestschool" -ne 10 ]; do
	printf "Best School\n";
	if [[ "$bestschool" -eq 7 ]]; then
		printf "good luck\n";
	elif [[ "$bestschool" -eq 4 ]]; then
	       printf "bad luck\n"	
	fi
	((bestschool++))
	
done;	
