#!/usr/bin/env bash
#this my script bash

bestschool=0;

while [ "$bestschool" -ne 10 ]; do

	if [[ "$bestschool" -eq 7 ]]; then
		printf "good luck\n";
	elif [[ "$bestschool" -eq 3 ]]; then
	       printf "bad luck\n"
       else 
	      printf "Best School\n" 
	fi
	((bestschool++))
	
done;	
