#!/usr/bin/env bash
#this my script bash
i=1
while [ $i -lt 20 ]
do
case $i in
4) printf "bad luck from China\n"
;;
8) printf "bad luck from Japan\n"
;;
16) printf "bad luck from Italy\n"
;;
*) echo "$i"
;;
esac
((i++))
done 
