#!/usr/bin/env bash
#school
if [[ -e school ]];then
	echo "school file exists"
elif [[ -s school ]];
	then
	echo "school file is not empty"
else
echo "school file is empty"
fi
if [[ -f school ]];
	then
	echo "school is a regular file"

else "school file does not exist"
fi
